dist: trusty

sudo: false

addons:
 apt:
   packages:
     - graphviz
     - cmake
     - pkg-config
     - python
     - ocl-icd-dev
     - libegl1-mesa-dev
     - ocl-icd-opencl-dev
     - libdrm-dev
     - libxfixes-dev
     - libxext-dev
     - llvm-3.6-dev
     - clang-3.6
     - libclang-3.6-dev
     - libtinfo-dev
     - libedit-dev
     - zlib1g-dev
     - fglrx-updates-core
     - fglrx-core

language: scala

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt +test

before_deploy:

deploy:
  skip_cleanup: true
  provider: script
  script: sbt "release with-defaults"
  on:
    condition: -e ./deploy.sbt
    all_branches: true
